name: Deploy Blog

on: [push] # 当有新push时运行

jobs:
  build: # 一项叫做build的任务
    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    steps:
      - name: Checkout # 任务名：将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkout
        
      - name: Use Node.js 16.x # 配置Node环境
        uses: actions/setup-node@v3 # 配置脚本来自 https://github.com/actions/setup-node
        with:
          node-version: "16.x"

      - name: install deps
        run: npm install
      - name: build artifact
        run: npm run build
      - name: check artifact
        run: |
          cd ${{ github.workspace }}
          ls
          cd dist
          ls
      - name: deploy(artifact)
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ${{ github.workspace }}/dist/**/*